# This is the config file for LodeStar v1.0

# localized language support
language: en-US

# data store type ( sqlite | yaml )
storage-type: sqlite

# Note: use only one enabled/disabled list, and comment out or remove the other
# enabled worlds list (use this list for a default-deny world policy)

#enabled-worlds:
#  - enabled_world1
#  - enabled_world2

# disabled worlds list (use this list for a default-allow world policy)

disabled-worlds:
  - disabled_world1
  - disabled_world2

# material to be used as default item. Set item data using a colon, example: WOOL:5
# invalid item data may be reset, so use only valid item data values for a given material
default-material: NETHER_STAR

# allow giving and binding with items of default material only
default-material-only: false

# minimum distance from destination to use
minimum-distance: 10

# cooldown time in seconds
teleport-cooldown: 60

# warmup time in seconds
teleport-warmup: 5

# particle effects during warmup
particle-effects: true

# play sound effects
sound-effects: true

# lightning strike at destination on use
lightning: true

# require shift-click to use LodeStar item
shift-click: true

# remove item from inventory ( on-use | on-success | never )
remove-from-inventory: on-success

# allow LodeStar items to be used in crafting recipes
allow-in-recipes: false

# cancel teleport if player takes damage
cancel-on-damage: false

# cancel teleport if player moves
cancel-on-movement: false

# cancel teleport if player interacts with another block
cancel-on-interaction: false

# maximum number of spawn star items that can be given at once (-1 for no limit)
max-give-amount: -1

# if player is in netherworld, try to respawn in matching overworld
from-nether: true

# if player is in end world, try to respawn in matching overworld
from-end: true

# write log entry on use
log-use: true

# sound configuration
sounds:
  command-fail:
    enabled: true
    player-only: true
    sound: VILLAGER_NO
    volume: 1
    pitch: 1
    
  command-success-give-sender:
    enabled: true
    player-only: true
    sound: SHOOT_ARROW
    volume: 1
    pitch: 0.5

  command-success-give-target:
    enabled: true
    player-only: true
    sound: ITEM_PICKUP
    volume: 1
    pitch: 1

  command-success-delete:
    enabled: true
    player-only: true
    sound: IRONGOLEM_HIT
    volume: 1
    pitch: 1

  command-success-destroy:
    enabled: true
    player-only: true
    sound: ITEM_BREAK
    volume: 1
    pitch: 1
    
  command-success-set:
    enabled: true
    player-only: true
    sound: LEVEL_UP
    volume: 1
    pitch: 1.5
    
  command-success-bind:
    enabled: true
    player-only: true
    sound: ANVIL_LAND
    volume: 1
    pitch: 1.75

  teleport-denied-permission:
    enabled: true
    player-only: true
    sound: FIZZ
    volume: 1
    pitch: 1
    
  teleport-cancelled:
    enabled: true
    player-only: false
    sound: FIZZ
    volume: 1
    pitch: 1
    
  teleport-cancelled-no-item:
    enabled: true
    player-only: false
    sound: ANGRY_DONKEY
    volume: 1
    pitch: 1
  
  teleport-warmup:
    enabled: true
    player-only: false
    sound: PORTAL_TRAVEL
    volume: 0.3
    pitch: 1
    
  teleport-success-departure:
     enabled: true
     player-only: false
     sound: ENDERMAN_TELEPORT
     volume: 1
     pitch: 1
  
  teleport-success-arrival:
     enabled: true
     player-only: false
     sound: ENDERMAN_TELEPORT
     volume: 1
     pitch: 1
